services: # 실행할 여러 서비스를 지정하는곳
  postgres: # 'postgres' 라는 이름의 서비스를 설정
    image: postgres:15
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data # 현재 HOST OS 위치 : 이미지 내부의 위치
    #docker image 안에서 생성된 파일 / 데이터를 HOST OS 의 Volume 과 매핑
    ports:
      - "5432:5432" # HOST 의 5432 port 가 이미지의 5432 포트로 연결됌
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # 기본으로 사용할 db 이름
