services:
    typeorm:
        image: postgres:15
        restart: always
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: typeorm
